### ISSUE TITLE
Please add standard option

### ISSUE THREAD

**Issue by Schrotty74** [UndertakerBen/PorThunderbirdUpd#2]
On the Edge or Chrome Portable i can make this as standard browser but on Thunderbird i can not do this. Can you add this feature please?

**Comment by UndertakerBen** [comment]
Now I have released an updated version of the updater where the launchers can be registered as default.

**Comment by Schrotty74** [comment]
I have test but not work. Get this error whene i cklick on a email.

https://ibb.co/wQtXjhk
